### ISSUE TITLE
0 bytes photo

### ISSUE THREAD

**Issue by maajja** [juliendu11/Instagram-Downloader#3]
success download image but size of photo is 0 bytes, is that problem from my internet??

**Comment by juliendu11** [comment]
> success download image but size of photo is 0 bytes, is that problem from my internet??

Hello, 

Is the url format good? (https://www.instagram.com/p/xxxxxxxx/)

Is the publication from a public account?

**Comment by maajja** [comment]
yes sir, the example i use this (https://www.instagram.com/p/CMQS42mlynS/) and the account is public

**Comment by juliendu11** [comment]
> ![0byts](https://user-images.githubusercontent.com/79619000/112091629-5a525f80-8bc8-11eb-8506-885af3145007.jpg)
> yes sir, the example i use this (https://www.instagram.com/p/CMQS42mlynS/) and the account is public

Weird, what system are you on? Windows, Linux or MacOS?

You save the media on which path, absolute or relative?
